# Generated by Django 4.1.7 on 2023-06-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcv', '0002_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
