# Generated by Django 4.1.7 on 2023-06-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcv', '0005_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='institute',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='certification',
            field=models.CharField(max_length=180),
        ),
    ]
