# Generated by Django 4.1.7 on 2023-06-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcv', '0006_education_institute_alter_education_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('background_colour', models.CharField(max_length=10)),
                ('font', models.CharField(max_length=20)),
            ],
        ),
    ]
