# Generated by Django 4.1.7 on 2023-06-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcv', '0007_customize'),
    ]

    operations = [
        migrations.AddField(
            model_name='customize',
            name='font_colour',
            field=models.CharField(default='black', max_length=20),
            preserve_default=False,
        ),
    ]
