# Generated by Django 4.1.7 on 2023-06-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcv', '0008_customize_font_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customize',
            name='background_colour',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='customize',
            name='font',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='customize',
            name='font_colour',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='customize',
            name='name',
            field=models.CharField(max_length=180),
        ),
    ]
