# Generated by Django 4.1.7 on 2023-07-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcv', '0010_customize_align'),
    ]

    operations = [
        migrations.AddField(
            model_name='customize',
            name='style',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
